# Generated by Django 3.2.5 on 2023-01-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_quanity_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity_as_float',
            new_name='quantity_as_float',
        ),
    ]
